---
title: "Modeling"
author: "Sarah Torrence"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, error = F)

# Box access
library(boxr)
box_auth()

library(ggplot2)
library(rms)

#read in data
data <- box_read("936748103348")
```


```{r}
convert <- c('ascites_yn', 'he', 'race', 'sex', 'smoker', 'etiology', 'acr',
             'newmalignancy', 'readmissionwithin90d',
             'infection_90', 'need_repeat_surgery',
             'vascularcomplicationswithin90days', 'biliarycomplication', 
             'htn', 'dm', 'ckd', 'ctd')

for (var in convert){
  data[var] <- as.factor(data[[var]])
}

data$state <- factor(data$state,
levels = c(1,2,3,4,5,6),
labels = c("Home", "Inpatient Rehab", "Hospital", "ICU", "Ventilator", "Dead"))

data$prev_state <- factor(data$prev_state,
levels = c(1,2,3,4,5,6),
labels = c("Home", "Inpatient Rehab", "Hospital", "ICU", "Ventilator", "Dead"))
```

```{r}
f <- orm(state ~ age, data = data)
f
```

```{r}
d <- data %>% filter(time < 29)

propsTrans(state ~ time + patient_mrn, data=d, maxsize=6) +
  theme(legend.position='bottom', axis.text.x=element_text(angle=90, hjust=1))
```

```{r}
propsPO(state ~ time, data=d, nrow=1) +
  theme(legend.position='bottom', axis.text.x=element_text(angle=90, hjust=1))
```

```{r}
f <- lrm(state ~ rcs(time, 5), data=d)
g <- Function(f)   # derive predicted log odds as a function of day
# Make another function that gets the OR vs. day=1
dor <- function(time) exp(g(time) - g(1))
propsPO(state ~ time, odds.ratio=dor, data=d) +
  theme(legend.position='bottom')
```

```{r}
f <- lrm(state ~ rcs(time, 5) + rcs(age, 5),
         data=d, tol=1e-13, x=TRUE, y=TRUE)
g <- robcov(f, d$patient_mrn)
plot(anova(g), trans=sqrt)
```

```{r}
g
```

