---
title: "Summary Statistics"
author: "Sarah Torrence"
output:
  html_document:
    highlight: espresso
    code_folding: hide
    toc_float:
      collapsed: true
---
      
```{r setup, echo=FALSE, cache=FALSE, warning=FALSE,message=FALSE}
library(vtable)
library(rms)

library(boxr)
box_auth()

data <- box_read("930224826408")
```

Here  are some summary statistics of representative variables in the data set stratified by gender.

```{r,message=FALSE}
library(table1)
data$sex <- factor(data$sex,
                        levels = c(1,0),
                        labels = c("Female", "Male"))

data$etiology <- factor(data$etiology,
                        levels = c(0, 1, 2, 3, 4),
                        labels = c("Non-Alcoholic Steatohepatitis", "Alcoholic Steatohepatitis", "Viral", "Autoimmune", "Other"))

label(data$age) <- "Age"
label(data$meld) <- "MELD Score"
label(data$index_los) <- "Hospital LOS"
label(data$etiology) <- "Etiology of Liver Disease"
label(data$bmi_pre) <- "BMI"

table1(~ age + meld + index_los + etiology + bmi_pre | sex, data=data, topclass="Rtable1-zebra")
```


### More detailed descriptive statistics about each variables are shown below.

This includes all original variables in addition to newly derived variables.

```{r}
html(describe(data, scroll=T))
```



